### ISSUE TITLE
Quick Start Error

### ISSUE THREAD

**Issue by way-of-sunvox** [metrasynth/radiant-voices#16]
After following install instructions, when running python helloworld.py I'm getting this error:

Traceback (most recent call last):
  File "helloworld.py", line 8, in <module>
    from rv.modules import Fm
ImportError: No module named rv.modules

Any help appreciated, thanks

**Comment by gldnspud** [comment]
@way-of-sunvox The example is now fixed and will be included in the next release.

Sorry for the late response!
