### ISSUE TITLE
Detach module ?

### ISSUE THREAD

**Issue by jhw** [metrasynth/radiant-voices#20]
Hi,

How do u detach a module from a project and attach it to another one ? Does it need to be explicitly detached / cloned to remove the original module index ? I get the following -

```
 File "/home/justin/work/seavox/lib/python3.6/site-packages/rv/project.py", line 70, in attach_module
    module.index = self.module_index(module)
AttributeError: 'str' object attribute 'index' is read-only
``` 

so wondering if there is any support for such a thing.

Thx!

**Comment by gldnspud** [comment]
@jhw do you still need help with this?

You can clone modules like so:

```python
from rv.api import Project, m
p, p2 = Project(), Project()
amp = p.new_module(m.Amplifier)
amp2 = p2.attach_module(amp.clone())
```

I think you may have shed light on a missing API though... `Project.detach_module(module)` should let you detach a module just as you can attach one. Detaching a module would also mean disconnecting it from all other modules.

Also, I don't think already-attached modules should be able to be attached to other projects without first being detached, as this could cause problems.

In light of this, I'm going to reopen this issue and take care of those issues soon.

**Comment by gldnspud** [comment]
@jhw you can now try this if you like 😄 

```python
from rv.api import Project, m
p, p2 = Project(), Project()
amp = p.new_module(m.Amplifier)
assert amp.parent is p
p2.attach_module(p.detach_module(amp))
assert amp.parent is p2
```

**Comment by jhw** [comment]
Yeah I closed it as I got round it by simply creating a new module with the
same controller values. But yeah, I think a detach() API is a nice
addition. Will try it, many thanks!

**Comment by jhw** [comment]
Working on this

https://github.com/jhw/seavox/blob/master/README.md

I will probably have some pull requests for Radiant Voices shortly

**Comment by jhw** [comment]
Also this, related

https://github.com/jhw/sunbeam/blob/master/README.md

U might want to watch the two of them and I'll do the same for RV
