### ISSUE TITLE
Access rights ?

### ISSUE THREAD

**Issue by jhw** [metrasynth/radiant-voices#21]
I wanted to push a feature branch and issue a pull request, but got the following -

```
radiant-voices) justin@justin-XPS-13-9360:~/work/radiant-voices$ git push origin jhw-writers
ERROR: Permission to metrasynth/radiant-voices.git denied to jhw.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Would like to collaborate, not done much Github collaboration before, are feature branches + pull requests the way to go ? If so could I get the correct permissions ?

Thx!

**Comment by jhw** [comment]
Maybe I should be forking RV and creating feature branches from that ? Or do you want to add me as a collaborator ? What's your preference ?

**Comment by gldnspud** [comment]
@jhw I'm comfortable with adding you as a collaborator and just did so. I'll start committing to feature branches and creating PRs too since I'm no longer the only active user of the project. 😄
