### ISSUE TITLE
Introduce shorthand API for connecting and disconnecting modules

### ISSUE THREAD

**Issue by gldnspud** [metrasynth/radiant-voices#6]

**Comment by gldnspud** [comment]
@zeffii your connection shorthand suggestion has been implemented: https://github.com/metrasynth/radiant-voices/blob/d6c6441e58d2f61dd9a0387b03fd5566e77bb22e/tests/modules/test_shorthand.py#L8-L9

**Comment by zeffii** [comment]
very cool, I have 32bits anaconda python 3.5 installed now + time for testing later today!
